### ISSUE TITLE
frame issue

### ISSUE THREAD

**Issue by antons81** [madjid/MMPickerView#28]
Please fix hard-coded width frame size
//PickerView Container with top bar
  _pickerContainerView = [[UIView alloc] initWithFrame:CGRectMake(0.0, _pickerViewContainerView.bounds.size.height - 260.0, [[UIScreen mainScreen]bounds].size.width, 260.0)]; // before width was 320.0

**Comment by multinerd** [comment]
it appears this project hasnt been maintained in over 3 years, i have a fork with a working fix [here](https://github.com/multinerd/MMPickerView)

if your using cocoapods, you can also use

> pod 'MMPickerView', :git => 'https://github.com/multinerd/MMPickerView.git'

i got tired of modifying the code everytime i needed to use this framework

**Comment by antons81** [comment]
Thank you :)
